# Generated by Django 4.2.7 on 2023-11-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_person_school_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
